version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: trendyol-clone-frontend
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: trendyol-clone-backend
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    build: ./database 
    container_name: trendyol-clone-database
    ports:
      - "8091-8095:8091-8095"
      - "11210:11210"
      - "18091:18091"
    environment:
      - COUCHBASE_BUCKET=trendyol-clone
      - COUCHBASE_ADMIN_USER=tyadmin
      - COUCHBASE_ADMIN_PASSWORD=typassword
    volumes:
      - couchbase_data:/opt/couchbase/var

volumes:
  couchbase_data:
