version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: trendyol-clone-frontend
    ports:
      - "3000:3000"

  database:
    build: ./database 
    container_name: trendyol-clone-database
    ports:
      - "8091-8095:8091-8095"
      - "11210:11210"
      - "18091:18091"
    environment:
      - COUCHBASE_BUCKET=mybucket
      - COUCHBASE_ADMIN_USER=admin
      - COUCHBASE_ADMIN_PASSWORD=password
    volumes:
      - couchbase_data:/opt/couchbase/data

volumes:
  couchbase_data:
